<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>warnings</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1701;1702;8602;CS1591</NoWarn>
    <UserSecretsId>463bcd4a-9650-47c7-b410-ba89bdeb272b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\bigquery-entity-poller\appsettings.development.json" Link="appsettings.development.json" Condition="Exists('..\bigquery-entity-poller\appsettings.development.json')">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Klpe.Shared.Common" Version="8.0.4" />
    <PackageReference Include="Klpe.Stylecop" Version="1.0.28" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Npgsql" Version="8.0.9" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RisingWavePollerCommon\RisingWavePollerCommon.csproj" />
  </ItemGroup>

</Project>
