"""
deploy_sink_views.py — Deploy parallel queryable views for all RisingWave sinks.

Usage:
    python deploy_sink_views.py <env_file> <dbt_target> <use_port_forward> [--select snk_foo snk_bar] [--all]

Creates or replaces standard SQL VIEWs (e.g. public."v_snk_customer_bq") matching
the exact projection of each sink.

Cost in RisingWave:
    - 0 streaming actors (actors = 0)
    - 0 memory / state
    - 0 background CPU
    - 0 impact on running sinks (no DROP SINK, no re-sync triggered)
"""

import glob
import os
import re
import sys
from pathlib import Path

import psycopg2


def load_env_file(env_file: str) -> dict:
    env = {}
    if not env_file or not os.path.exists(env_file):
        return env
    with open(env_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, _, value = line.partition('=')
            env[key.strip()] = value.strip()
    return env


def clean_sink_query(raw_sql: str) -> str:
    """Extract clean SELECT/WITH query from compiled sink SQL."""
    # Remove #id test column line generated by test_id() macro
    s = re.sub(
        r'^\s*.*AS\s+["\']?#id["\']?,?\s*$',
        '',
        raw_sql,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)   # block comments
    s = re.sub(r"(?m)--.*$", "", s)                # line comments

    # Handle CREATE SINK ... FROM <relation> syntax
    m_from = re.search(r"(?is)\bCREATE\s+SINK\b.*?\bFROM\s+([^\s;()]+)", s)
    if m_from:
        relation = m_from.group(1).strip()
        return f"SELECT * FROM {relation}"

    s = re.sub(r"(?is)^.*?\bCREATE\s+SINK\b.*?\bAS\b\s+", "", s, count=1)  # CREATE SINK header
    s = re.sub(r"(?is)\bWITH\s*\([^)]*\bconnector\b.*$", "", s)            # trailing connector
    return s.strip().rstrip(";").strip()


def find_compiled_sinks(dbt_dir: Path) -> dict[str, str]:
    """Find all compiled sink SQL files in target/compiled."""
    pattern = str(dbt_dir / "target" / "compiled" / "*" / "models" / "sinks" / "snk_*.sql")
    files = glob.glob(pattern)
    sinks = {}
    for fpath in files:
        stem = Path(fpath).stem  # e.g. snk_customer_bq
        with open(fpath, "r", encoding="utf-8") as f:
            sinks[stem] = f.read()
    return sinks


def deploy_views(conn, sinks: dict[str, str], selected: set[str] | None = None) -> tuple[int, int]:
    deployed = 0
    failed = 0

    with conn.cursor() as cur:
        for sink_name, raw_sql in sorted(sinks.items()):
            if selected and sink_name not in selected:
                continue

            view_name = f"v_{sink_name}"
            query = clean_sink_query(raw_sql)
            ddl_drop = f'DROP VIEW IF EXISTS public."{view_name}" CASCADE;'
            ddl_create = f'CREATE VIEW public."{view_name}" AS\n{query};'

            try:
                cur.execute(ddl_drop)
                cur.execute(ddl_create)
                conn.commit()
                deployed += 1
                print(f"  CREATE VIEW public.\"{view_name}\" ... OK")
            except Exception as exc:
                conn.rollback()
                failed += 1
                print(f"  ERROR creating view public.\"{view_name}\": {exc}", file=sys.stderr)

    return deployed, failed


def main():
    if len(sys.argv) < 4:
        print(
            "Usage: deploy_sink_views.py <env_file> <dbt_target> <use_port_forward> [--select ... | --all]",
            file=sys.stderr,
        )
        sys.exit(1)

    env_file = sys.argv[1]
    dbt_target = sys.argv[2]
    use_port_forward = sys.argv[3].lower() == "true"
    extra_args = sys.argv[4:]

    selected = None
    if "--select" in extra_args or "-s" in extra_args:
        idx = extra_args.index("--select") if "--select" in extra_args else extra_args.index("-s")
        selected = set(extra_args[idx + 1:])

    script_dir = Path(__file__).parent
    dbt_dir = script_dir.parent

    sinks = find_compiled_sinks(dbt_dir)
    if not sinks:
        print("  WARNING: No compiled sink files found. Run `dbt compile` first.", file=sys.stderr)
        return

    env_vars = load_env_file(env_file)

    if use_port_forward:
        host, user, password, port = "localhost", "root", "", 4566
    else:
        host = env_vars.get("DBT_RW_HOST", "localhost")
        user = env_vars.get("DBT_RW_USER", "root")
        password = env_vars.get("DBT_RW_PASSWORD", "")
        port = int(env_vars.get("DBT_RW_PORT", "4566"))

    dbname = env_vars.get("DBT_RW_DBNAME", dbt_target if dbt_target not in ("localdev", "ci") else "dev")

    try:
        conn = psycopg2.connect(host=host, port=port, user=user, password=password, dbname=dbname)
        print(f"==> Deploying parallel queryable sink views (v_snk_*) to {dbname}...")
        deployed, failed = deploy_views(conn, sinks, selected=selected)
        conn.close()
        print(f"==> Successfully deployed {deployed} sink view(s) ({failed} failed).")
    except Exception as exc:
        print(f"WARNING: Could not connect to RisingWave to deploy sink views: {exc}", file=sys.stderr)


if __name__ == "__main__":
    main()
