{{ config(
    materialized='table_with_connector'
) }}

CREATE TABLE {{ this }} (
    _id                    VARCHAR         PRIMARY KEY,
    saleId                 BIGINT,
    visibleFor             VARCHAR,
    date                   VARCHAR,
    heading                VARCHAR,
    currency               VARCHAR,
    competitor             VARCHAR,
    lossReason             VARCHAR,
    source                 VARCHAR,
    credited               VARCHAR,
    userGroup              VARCHAR,
    saleStatus             VARCHAR,
    amount                 DOUBLE PRECISION,
    earning                DOUBLE PRECISION,
    earningPercent         DOUBLE PRECISION,
    saleNumber             VARCHAR,
    associateId            VARCHAR,
    personId               BIGINT,
    contactId              BIGINT,
    projectId              BIGINT,
    projectName            VARCHAR,
    currencyId             BIGINT,
    nextDueDate            VARCHAR,
    saleType               VARCHAR,
    stalledComment         VARCHAR,
    soldReason             VARCHAR,
    activeErpLinks         BOOLEAN,
    probPercent            DOUBLE PRECISION,
    reOpenDate             VARCHAR,
    registeredBy           VARCHAR,
    registeredDate         VARCHAR,
    hasGuide               BOOLEAN,
    hasStakeholders        BOOLEAN,
    completed              VARCHAR,
    icon                   VARCHAR,
    type                   VARCHAR,
    stage                  VARCHAR,
    originalStage          VARCHAR,
    hasQuote               BOOLEAN,
    text                   VARCHAR,
    description            VARCHAR,
    updatedBy              VARCHAR,
    updatedDate            VARCHAR,
    who                    VARCHAR,
    primaryKey             BIGINT,
    entityName             VARCHAR
);
