{{ config(
    materialized='table_with_connector'
) }}

CREATE TABLE {{ this }} (
    _id             VARCHAR PRIMARY KEY,
    aarlig_beloep       DOUBLE PRECISION,
    antall                  DOUBLE PRECISION,
    areal                   DOUBLE PRECISION,
    areal_ikke_medregnet    DOUBLE PRECISION,
    areal_type              VARCHAR,
    areal_type_navn         VARCHAR,
    borett_fra              TIMESTAMPTZ,
    borett_til              TIMESTAMPTZ,
    faktura_fra             TIMESTAMPTZ,
    faktura_til             TIMESTAMPTZ,
    firma                   VARCHAR,
    fysisk_areal            DOUBLE PRECISION,
    gyldig_fra              TIMESTAMPTZ,
    gyldig_til              TIMESTAMPTZ,
    kontrakt_linje_id   VARCHAR,    
    kontrakt_nummer     VARCHAR,
    leie_antall         DOUBLE PRECISION,
    leie_art_gruppe_id  BIGINT,
    leie_art_gruppe_kode VARCHAR,
    leie_art_gruppe_n1  VARCHAR,
    leie_enhet          VARCHAR,
    leie_kost_gruppe_id BIGINT,
    leie_kost_type_id   VARCHAR,
    leie_kost_type_navn VARCHAR,
    leie_objekt_id      VARCHAR,
    leie_objekt_navn    VARCHAR,
    linje_type          INT,
    lopende             VARCHAR,
    maanedlig_beloep    DOUBLE PRECISION,
    navn                VARCHAR,
    reservert_fra       TIMESTAMPTZ,
    reservert_til       TIMESTAMPTZ,
    kontrakt_dato       TIMESTAMPTZ,
    lokal_valuta        VARCHAR,
    unik_id             BIGINT,
    status_kode         INT,
    status_navn         VARCHAR,
    frist_oppsigelse_leietaker VARCHAR,
    frist_oppsigelse_utleier   VARCHAR,
    frist_reforhandling        VARCHAR,
    frist_reg_varsel           VARCHAR,
    oppsdato_leietaker         TIMESTAMPTZ,
    oppsdato_utleier           TIMESTAMPTZ,
    begjaeret_utkastet          TIMESTAMPTZ,
    faktisk_utkastet           TIMESTAMPTZ,
    _is_active                 BOOLEAN,
    FirstPossibleTerminationDate TIMESTAMPTZ,
    FirstPossibleTerminationDateLessor TIMESTAMPTZ
);
