<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Klpe.Stylecop" Version="1.0.28" />
    <PackageReference Include="Klpeiendom.Api.Shared.Doc.Swagger" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.18" />
    <PackageReference Include="Npgsql" Version="8.0.9" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Klpe.Shared.Common" Version="8.0.4" />
    <PackageReference Include="Klpeiendom.Shared.Authentication" Version="8.0.5" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="swagger_settings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="swagger_settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
